name: Run Test

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Start xcode build 🛠
      run: xcodebuild build -project MC3-Team5-CleanArea/Yeowoo.xcodeproj
